-- Event store schema reference for the task_events table.
--
-- ⚠️  THIS FILE IS DOCUMENTATION ONLY — it does NOT create any tables.
--
-- The authoritative task_events DDL lives exclusively in the migration system:
--
--   backend/src/db/migrations/tasks/002_create_task_events_table.up.sql
--     → creates the legacy schema B (id, taskId, type, nodeId, payload, timestamp)
--
--   backend/src/db/migrations/tasks/005_replace_task_events_schema.up.sql
--     → transforms schema B into the canonical schema A (below)
--
-- Production databases receive schema A by running these migrations in order.
-- In-memory and test databases use the same two migration files (applied by
-- createEventStore() in src/events/eventStore.ts).
--
-- Do NOT add CREATE TABLE / CREATE INDEX statements to this file.  Any DDL
-- change must go through a new numbered migration so that deployed databases
-- can be upgraded safely and checksums stay consistent.
--
-- ─── Schema A (canonical) ────────────────────────────────────────────────
--
-- CREATE TABLE task_events (
--   global_seq  INTEGER PRIMARY KEY AUTOINCREMENT,  -- cross-task ordering
--   task_seq    INTEGER NOT NULL,                   -- per-task cursor (EventBus)
--   version     INTEGER NOT NULL DEFAULT 1,         -- payload schema version
--   type        TEXT    NOT NULL,                   -- event discriminator
--   task_id     TEXT    NOT NULL,                   -- owning task
--   node_id     TEXT,                               -- DAG node (NULL = task-level)
--   occurred_at TEXT    NOT NULL,                   -- ISO-8601 wall-clock time
--   payload     TEXT,                               -- JSON payload (may be NULL)
--   UNIQUE (task_id, task_seq)
-- );
--
-- CREATE INDEX idx_events_task_seq    ON task_events (task_id, task_seq ASC);
-- CREATE INDEX idx_events_occurred_at ON task_events (occurred_at ASC);
-- CREATE INDEX idx_events_type        ON task_events (type, occurred_at ASC);
--
-- See also: docs/architecture/index.md §5, docs/EVENTS.md
